### ISSUE TITLE
Answer Not Accepted (But is Correct)

### ISSUE THREAD

**Issue by Eliea944** [10se1ucgo/LoLTrivia#1]
![image](https://user-images.githubusercontent.com/32571222/31277725-e5b89518-aad4-11e7-9c31-3340e09cd7d6.png)

**Comment by 10se1ucgo** [comment]
Thanks, I'll take a look into my logs. 

First to help me narrow it down, can you tell me if the bot had previously accepted any of your answers? Also your discord `name#discriminator` or ID would be helpful

**Comment by 10se1ucgo** [comment]
No response.
