### ISSUE TITLE
Huh, I get a UrlLib error when trying to selfhost the bot

### ISSUE THREAD

**Issue by codingJWilliams** [10se1ucgo/LoLTrivia#2]
I'm using Python 3.6, cassiopeia 0.1.4 and Ubuntu 16.04.
This is the error I get: https://coding.has-destroyed.me/ufbeXbaJ

I've forked your repo if that's the issue, not sure what's wrong D:

**Comment by codingJWilliams** [comment]
Also I'm selfhosting because I want to modify the bot slightly, but I haven't changed anything yet

**Comment by codingJWilliams** [comment]
@10se1ucgo

**Comment by 10se1ucgo** [comment]
I'm using a patched version of old cassiopeia updated to work with the new version of the static data API. The old API was deprecated (and removed iirc) and you likely can't connect to it. [Try using this version.](https://www.dropbox.com/s/oybzqatgoso90hi/cassiopeia.7z?dl=0) Just put it in the same directory as run.py

**Comment by codingJWilliams** [comment]
Thanks bro, Trying that now. I appreciate github people who reply to issues

**Comment by codingJWilliams** [comment]
And your bot is dope

**Comment by codingJWilliams** [comment]
It works, thanks! Your bot is a smash hit on our server and I wanted to integrate it with our server economy. Thanks dude

**Comment by codingJWilliams** [comment]
Oh also, do you have a quotes and skins.json by any chance, or a place to get them? I'm a dev, not a LoL player and don't wanna have to do it manually xD
