### ISSUE TITLE
Quotes.json and skins.json

### ISSUE THREAD

**Issue by codingJWilliams** [10se1ucgo/LoLTrivia#3]
Is there any reason that you haven’t included quotes and skins.json into the repo? And is there any way you could send me them, I’m just a developer for a LoL server, I’ve never actually played it so I really don’t want to have to fill them in manually.
Also, is it cool if I pull request the patched cass library back in? Be nice to other devs

**Comment by codingJWilliams** [comment]
Sorry to bug you @10se1ucgo but I need this asap 🤣

**Comment by 10se1ucgo** [comment]
https://gist.github.com/10se1ucgo/9a5e84ee8c0cce51e04aca31d057c372

As for having cass in the main repo, I'd rather not, but I'll at least link it in the README.

**Comment by codingJWilliams** [comment]
Thanks <3
